// config/districts.yaml: `district: [owner/name, …]`. Unlisted repos → `uncategorized`.
// Entries may also be a bare repo `name` (matches any owner). Matching is case-insensitive.
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const DISTRICTS_PATH = join(
	import.meta.dir,
	"../../../../config/districts.yaml",
);
export const DISTRICTS_DRAFT_PATH = join(
	import.meta.dir,
	"../../../../config/districts.draft.yaml",
);
export const UNCATEGORIZED = "uncategorized";

export interface Districts {
	/** District names in file order (always includes `uncategorized`). */
	names: string[];
	districtOf(repoId: string): string;
	warnings: string[];
}

export function parseDistricts(yamlText: string): Districts {
	const parsed = (Bun.YAML.parse(yamlText) ?? {}) as Record<string, unknown>;
	if (typeof parsed !== "object" || Array.isArray(parsed)) {
		throw new Error("districts.yaml must be a mapping of district → list");
	}
	const byFull = new Map<string, string>();
	const byName = new Map<string, string>();
	const warnings: string[] = [];
	const names: string[] = [];

	for (const [district, list] of Object.entries(parsed)) {
		names.push(district);
		if (list == null) continue;
		if (!Array.isArray(list)) {
			warnings.push(`district "${district}" is not a list — ignored`);
			continue;
		}
		for (const raw of list) {
			if (typeof raw !== "string" || !raw.trim()) continue;
			const key = raw.trim().toLowerCase();
			const map = key.includes("/") ? byFull : byName;
			const prev = map.get(key);
			if (prev !== undefined) {
				if (prev !== district)
					warnings.push(
						`"${raw}" listed in both "${prev}" and "${district}" — keeping "${prev}"`,
					);
				continue;
			}
			map.set(key, district);
		}
	}
	if (!names.includes(UNCATEGORIZED)) names.push(UNCATEGORIZED);

	return {
		names,
		warnings,
		districtOf(repoId) {
			const id = repoId.toLowerCase();
			return (
				byFull.get(id) ??
				byName.get(id.slice(id.indexOf("/") + 1)) ??
				UNCATEGORIZED
			);
		},
	};
}

export function loadDistricts(path = DISTRICTS_PATH): Districts {
	return parseDistricts(readFileSync(path, "utf8"));
}

/**
 * A districts.yaml-shaped draft listing every known repo under its current district (so
 * `uncategorized` shows what still needs a home). Written to districts.draft.yaml, never to
 * districts.yaml.
 */
export function renderDistrictsDraft(
	repos: readonly { id: string; district: string; is_local_only: boolean }[],
	names: readonly string[],
	generatedAt: string,
): string {
	const groups = new Map<string, string[]>(names.map((n) => [n, []]));
	for (const r of [...repos].sort((a, b) => a.id.localeCompare(b.id))) {
		const list = groups.get(r.district) ?? [];
		const item = JSON.stringify(r.id);
		list.push(r.is_local_only ? `${item} # local-only` : item);
		groups.set(r.district, list);
	}
	const lines = [
		`# DRAFT generated by \`bun run districts:draft\` at ${generatedAt}. The hub does NOT read this file.`,
		"# Move repos out of `uncategorized` into a district, then copy the result into config/districts.yaml.",
		"# Contains private repo names — gitignored; don't commit or paste it anywhere public.",
		"",
	];
	for (const [district, list] of groups) {
		if (list.length === 0) {
			lines.push(`${district}: []`);
			continue;
		}
		lines.push(`${district}:`);
		for (const item of list) lines.push(`  - ${item}`);
	}
	return `${lines.join("\n")}\n`;
}
