// `bun run managed:demo` — deterministic demonstration of the managed pipeline. Simulated only:
// fake adapters on a throwaway fixture repository; no model, no provider CLI, no network.
//
//   bun run managed:demo              run the scenarios in a temp dir, print the outcomes, clean up
//   bun run managed:demo --init [dir] create a persistent fixture repo + managed.yaml for the web UI
//                                     (default dir: ~/.agentcity/managed-demo; nothing else is touched)
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import type { SimulationScenario } from "@agent-city/schema";
import { Orchestrator } from "./orchestrator.ts";
import { runTask, submitTask, taskDetail } from "./service.ts";
import { GIT, initFixtureRepo, makeFixture } from "./testkit.ts";
import { createAdapters } from "./worker.ts";

const SCENARIOS: SimulationScenario[] = [
	"approve",
	"reject_then_approve",
	"reject_always",
	"verification_fails_then_fixed",
	"verification_fails",
	"malformed_review",
	"reviewer_mutates",
	"no_changes",
];

async function runDemo(): Promise<number> {
	console.log(
		"Managed pipeline demo — SIMULATED. Fake adapters on a disposable fixture repo; no model is called.\n",
	);
	let unexpected = 0;
	const expected: Record<string, string> = {
		approve: "human_ready",
		reject_then_approve: "human_ready",
		reject_always: "failed",
		verification_fails_then_fixed: "human_ready",
		verification_fails: "failed",
		malformed_review: "failed",
		reviewer_mutates: "failed",
		no_changes: "failed",
	};
	for (const scenario of SCENARIOS) {
		const fx = makeFixture();
		try {
			const deps = { db: fx.db, config: fx.config };
			const { task } = await submitTask(deps, {
				idempotency_key: `demo-${scenario}-${Date.now()}`,
				repo_id: fx.repoId,
				title: `Demo: ${scenario}`,
				objective: "Demonstrate the managed pipeline on a fixture repository.",
				acceptance_criteria: ["The fixture check passes"],
				approved_scope: ["."],
				execution_mode: "simulated",
				simulation_scenario: scenario,
			});
			runTask(deps, task.id);
			const orch = new Orchestrator({
				db: fx.db,
				config: fx.config,
				adapters: createAdapters(fx.config),
			});
			while (await orch.tick()) {
				// drain
			}
			const d = await taskDetail(deps, task.id);
			const ok = d.task.state === expected[scenario];
			if (!ok) unexpected++;
			const label =
				d.task.state === "human_ready"
					? "simulated human-ready"
					: `${d.task.state} (${d.task.failure_kind})`;
			console.log(
				`${ok ? "ok  " : "FAIL"} ${scenario.padEnd(30)} → ${label.padEnd(36)} attempts ${d.runs.length}, reviews ${d.reviews.length}, artifacts ${d.artifacts.length}`,
			);
		} finally {
			fx.cleanup();
		}
	}
	console.log(
		unexpected === 0
			? "\nAll scenarios ended as expected. These are simulated results, not reviewed work."
			: `\n${unexpected} scenario(s) did not end as expected.`,
	);
	return unexpected === 0 ? 0 : 1;
}

function init(dirArg: string | undefined): number {
	const dir = resolve(dirArg ?? join(homedir(), ".agentcity", "managed-demo"));
	const repo = join(dir, "fixture-repo");
	const configPath = join(dir, "managed.yaml");
	if (existsSync(repo) || existsSync(configPath)) {
		console.error(
			`${dir} already holds a demo fixture — remove it or pass another directory.`,
		);
		return 1;
	}
	mkdirSync(dir, { recursive: true });
	initFixtureRepo(repo);
	writeFileSync(
		configPath,
		`# Generated by \`bun run managed:demo --init\`. Simulated runs only (live is off).
workspace_root: ${join(dir, "workspaces")}
artifacts_root: ${join(dir, "artifacts")}
git_executable: ${GIT}
repos:
  - id: local/fixture-repo
    path: ${repo}
    base_ref: main
    verification:
      - name: fixture-check
        argv: ["/bin/sh", "verify.sh"]
        timeout_s: 30
live:
  enabled: false
`,
	);
	console.log(`Created a disposable fixture repo and config under ${dir}

Add to your .env (yourself — this script never writes .env):
  MANAGED_CONFIG=${configPath}
  MANAGED_TOKEN=<a long random string, e.g. from: openssl rand -hex 32>

Then: bun run dev → open the web UI → "Managed tasks" → paste the token → create a simulated task.`);
	return 0;
}

if (import.meta.main) {
	const args = process.argv.slice(2);
	const code = args[0] === "--init" ? init(args[1]) : await runDemo();
	process.exit(code);
}
